function testSpectrumSense

[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX_2;

while true
    decisions = SpectrumSenseEnergy( ObjAGC, ObjSDRuReceiver, tx );
    for k=1:10
        fprintf('Decision %d: %f\n',int16(k),int16(decisions(k)));
    end
end

end