function [previousMessage, msgStatus] = MACLayerTransmitter(...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits,...
    message,...
    previousMessage,...
    recipient...
    )

%% This function is called when the node wants to transmit something

DebugFlag = 0;

% Preinitialize
maxRetries = 6;
msgStatus = false;

% % Sense spectrum and wait until it is unoccupied
% for tries = 1:4 % try only so many times
%     [occupied,meanEnergy] = SpectrumSenseEnergy( ObjAGC, ObjSDRuReceiver, tx );
%     fprintf('MAC| Energy Measured: %f\n',meanEnergy);
%     if occupied
%         %fprintf('MAC| Spectrum occupied, listening...\n');
%         %Recover signal and/or wait
%         lookingForACK = false;
%         [~, previousMessage] = MACLayerReceiver(...
%             ObjAGC,...           %Objects
%             ObjSDRuReceiver,...
%             ObjSDRuTransmitter,...
%             ObjDetect,...
%             ObjPreambleDemod,...
%             ObjDataDemod,...
%             estimate,...         %Structs
%             tx,...
%             timeoutDuration,...  %Values/Vectors
%             messageBits,...
%             lookingForACK,...
%             previousMessage...
%             );
%         
%     else% Yay we can transmit now
%         break;
%     end
%     if tries >=4
%         fprintf('MAC| Spectrum Busy, try again later\n');
%         return;
%     end
% end


% Adjust offset for node
%fprintf('Transmitting to node: %d, with offset: %f\n',int16(recipient),tx.offsetTable(recipient));
ObjSDRuTransmitter.CenterFrequency = tx.CenterFrequency + tx.offsetTable(recipient);


%% Spectrum clear, send message
for tries = 1:maxRetries
    % Send message
    PHYTransmit(...
        ObjSDRuTransmitter,...
        ObjSDRuReceiver,...
        message,...
        tx.samplingFreq,...
        tx.nodeNum,...%originator
        recipient...%destination
        );
    % Listen for acknowledgement
    %fprintf('###########################################\n');
    if DebugFlag;fprintf('MAC| Transmission finished, waiting for ACK\n');end;
    % Call Receiver
    lookingForACK = true;
    [Response, previousMessage] = MACLayerReceiver(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        lookingForACK,...
        previousMessage...
        );

    if strcmp(Response,'ACK')
        if DebugFlag;fprintf('MAC| Got ACK\n');end
        msgStatus = true;
        break
    else
        if DebugFlag;fprintf('MAC| Retransmitting message\n');end;
    end
    if tries >= 4
        if DebugFlag
            fprintf('###########################################\n');
            fprintf('MAC| No ACK received :(\n');
            fprintf('###########################################\n');
        end
        return;
    end 
end


end

