function testMACReceiver(offsets, nodeNum)


% Create needed objects and structs
[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    tx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX_2;

lookingForACK = 0;

tx.offsetTable = offsets;
tx.nodeNum = nodeNum;

ObjSDRuReceiver.CenterFrequency = ObjSDRuReceiver.CenterFrequency + 1e6;

% Previous Message string holder
coder.varsize('previousMessage', [1, 80], [0 1]);
previousMessage = '';

for run = 1 : 1e8
    
    % MAC
    [~, previousMessage] = MACLayerReceiver(...
        ObjAGC,...           %Objects
        ObjSDRuReceiver,...
        ObjSDRuTransmitter,...
        ObjDetect,...
        ObjPreambleDemod,...
        ObjDataDemod,...
        estimate,...         %Structs
        tx,...
        timeoutDuration,...  %Values/Vectors
        messageBits,...
        lookingForACK,...
        previousMessage...
        );
    %Wait some time
    waitTime = 0.05; % Calculated in seconds buts thats far from realistic 
    Wait(ObjSDRuReceiver,tx.samplingFreq,waitTime);
    
end

end
