function testPHYReceive(offset)

[...
    ObjAGC,...           %Objects
    ObjSDRuReceiver,...
    ObjSDRuTransmitter,...
    ObjDetect,...
    ObjPreambleDemod,...
    ObjDataDemod,...
    estimate,...         %Structs
    rx,...
    timeoutDuration,...  %Values/Vectors
    messageBits...
    ] = CreateTXRX;

% Adjust offset for node
ObjSDRuReceiver.CenterFrequency = rx.CenterFrequency - offset;

while true
[recoveredMessage] = PHYReceive(...
                ObjAGC,...           %Objects
                ObjSDRuReceiver,...
                ObjDetect,...
                ObjPreambleDemod,...
                ObjDataDemod,...
                estimate,...         %Structs
                rx,...
                timeoutDuration,...  %Values/Vectors
                messageBits...
                );

            
            if ~strcmp(recoveredMessage,'CRC Error') && ~strcmp(recoveredMessage,'Timeout') 
                fprintf('Got Message: %s\n',recoveredMessage);
            end

end

end