function ObjSDRuReceiver = create_obj

x = dsp.FFT;
ObjSDRuReceiver = comm.SDRuReceiver( '192.168.10.2', ...
    'CenterFrequency',      2.2e9, ...
    'DecimationFactor',     20,...
    'FrameLength',          5120,...
    'OutputDataType',       'double',...
    'Gain',                 18);
end
