function testPHYTransmit

persistent  ObjAGC2...           %Objects
    ObjSDRuTransmitter2...
    ObjDetect2...
    ObjPreambleDemod2...
    ObjDataDemod2...
    estimate2...         %Structs
    tx2...
    timeoutDuration2...  %Values/Vectors
    messageBits2;


if isempty(ObjSDRuTransmitter2)
[...
    ObjAGC2,...           %Objects
    ObjSDRuTransmitter2,...
    ObjDetect2,...
    ObjPreambleDemod2,...
    ObjDataDemod2,...
    estimate2,...         %Structs
    tx2,...
    timeoutDuration2,...  %Values/Vectors
    messageBits2...
    ] = CreateTXRX_TX;

end


inputPayloadMessage2 = ['Hello World2'];

destNodeID2 = 1;

originNodeID2 = 2;

% Adjust offset for node
%ObjSDRuTransmitter.CenterFrequency = tx.CenterFrequency + offset;

for k=1:1e5
<<<<<<< HEAD
%fprintf('Transmitting\n');
PHYTransmit(...
    ObjSDRuTransmitter,...
    inputPayloadMessage,...
    tx.samplingFreq,...
    originNodeID,...
    destNodeID...
    );

=======
%fprintf('Starting Transmitter Loop\n');
	PHYTransmit(...
	    ObjSDRuTransmitter2,...
	    inputPayloadMessage2,...
	    tx2.samplingFreq,...
	    originNodeID2,...
	    destNodeID2...
	    );
>>>>>>> phyObj
end

end
